# Generated by Django 3.2.3 on 2021-05-24 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20210524_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 6, 32, 14, 441130, tzinfo=utc), verbose_name='زمان انتشار دوره'),
        ),
    ]
