# Generated by Django 3.2.3 on 2021-05-24 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_auto_20210524_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 8, 23, 28, 114285, tzinfo=utc), verbose_name='زمان انتشار دوره'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default='', max_length=244, verbose_name='فایل آموزششی'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=244, verbose_name='دسته')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='دامنه')),
                ('active', models.BooleanField(default=True, verbose_name="آیا 'دسته' فعال است ؟")),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eshop.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
                'ordering': ['-parent'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(related_name='courses', to='eshop.Category', verbose_name='دسته بندی'),
        ),
    ]
