# Generated by Django 3.2.3 on 2021-05-24 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_auto_20210524_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-active'], 'verbose_name': 'دسته', 'verbose_name_plural': 'دسته ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eshop.category', verbose_name='دسته والد'),
        ),
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 8, 37, 33, 50859, tzinfo=utc), verbose_name='زمان انتشار دوره'),
        ),
    ]
