# Generated by Django 3.2.3 on 2021-05-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_auto_20210524_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='eshop.course', verbose_name='دوره مربوط'),
        ),
    ]
