# Generated by Django 3.2.3 on 2021-05-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_alter_uploadfile_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='eshop.course', verbose_name='دوره مربوط'),
        ),
    ]
