# Generated by Django 3.2.3 on 2021-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_alter_uploadfile_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=244, null=True, verbose_name='مناسبت تخفیف')),
                ('expire', models.DateTimeField(verbose_name='تاریخ اتمام تخفیف')),
                ('percent', models.IntegerField(default=5, verbose_name='تخفیف (درصد)')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیفات',
            },
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(default='', max_length=244, verbose_name='فایل آموزشی'),
        ),
    ]
