# Generated by Django 3.2.3 on 2021-05-23 15:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import eshop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=244, verbose_name='دوره آموزشی')),
                ('file', models.FileField(upload_to=eshop.models.make_random_name, verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'فایل آموزشی',
                'verbose_name_plural': 'فایل های آموزشی',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=244, verbose_name='دوره آموزشی')),
                ('thumbnail', models.ImageField(upload_to=eshop.models.make_random_name, verbose_name='تصویر دوره')),
                ('description', models.TextField(verbose_name='شرح دوره')),
                ('price', models.IntegerField(help_text='قیمت را به "تومان" وارد کنید', verbose_name='قیمت دوره')),
                ('publish', models.DateTimeField(default=datetime.datetime(2021, 5, 23, 15, 9, 31, 381098, tzinfo=utc), verbose_name='زمان انتشار دوره')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='آیا دوره فعال است ؟')),
                ('status', models.CharField(choices=[('a', 'به زودی'), ('b', 'در حال بروزرسانی'), ('c', 'به اتمام رسیده'), ('d', 'متوقف شده')], max_length=1, verbose_name='وضعیت دوره')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='eshop.uploadfile', verbose_name='فایل های دوره')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'دوره آموزشی',
                'verbose_name_plural': 'دورهای آموزشی',
            },
        ),
    ]
