# Generated by Django 3.2.3 on 2021-05-23 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 15, 11, 24, 793188, tzinfo=utc), verbose_name='زمان انتشار دوره'),
        ),
    ]
