# Generated by Django 3.2.3 on 2021-05-24 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_alter_course_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=' ', unique=True, verbose_name='دامنه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 6, 31, 42, 954047, tzinfo=utc), verbose_name='زمان انتشار دوره'),
        ),
    ]
