# Generated by Django 3.2.3 on 2021-05-24 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20210524_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='eshop.uploadfile', verbose_name='فایل های دوره'),
        ),
        migrations.AlterField(
            model_name='course',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 7, 3, 12, 957735, tzinfo=utc), verbose_name='زمان انتشار دوره'),
        ),
    ]
