# Generated by Django 3.2.3 on 2021-05-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_alter_course_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course', to='eshop.course', verbose_name='فایل های دوره'),
        ),
    ]
