# Generated by Django 3.2.3 on 2021-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_auto_20210524_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='offcourse',
            name='active',
            field=models.BooleanField(default=True, verbose_name="آیا 'تخفیف' فعال است ؟"),
        ),
    ]
