# Generated by Django 3.2.3 on 2021-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0016_offcourse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='free',
            field=models.BooleanField(default=False, verbose_name='آیا این فایل رایگان است؟'),
        ),
    ]
