# Generated by Django 3.2.3 on 2021-05-26 14:20

from django.db import migrations, models
import eshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=244, verbose_name='دوره آموزشی')),
                ('banner', models.CharField(blank=True, max_length=244, null=True, verbose_name='شعار')),
                ('thumbnail', models.ImageField(upload_to=eshop.models.make_random_name, verbose_name='تصویر اسلایدر1920 * 900')),
                ('description', models.TextField(verbose_name='شرح کوتاه برای اسلایدر')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to=eshop.models.make_random_name, verbose_name='تصویر دوره 600 * 600'),
        ),
    ]
