# Generated by Django 3.2.3 on 2021-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0019_auto_20210526_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر ها'},
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(default='', verbose_name='لینک دوره'),
        ),
    ]
