# Generated by Django 3.2.3 on 2021-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0020_auto_20210526_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='active',
            field=models.BooleanField(default=True, verbose_name="آیا 'اسلایدر' فعال است ؟"),
        ),
    ]
