# Generated by Django 3.2.3 on 2021-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0021_slider_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='price',
            field=models.IntegerField(default=0, help_text='قیمت را به "تومان" وارد کنید', verbose_name='قیمت دوره'),
        ),
    ]
