# Generated by Django 3.2.3 on 2021-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0022_slider_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='color',
            field=models.CharField(default='', max_length=10, verbose_name='رنگ'),
        ),
    ]
