# Generated by Django 3.2.3 on 2021-08-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0023_slider_color'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart', verbose_name='سبد خرید')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.course', verbose_name='دوره آموزشی')),
            ],
            options={
                'verbose_name': 'دوره خریداری شده',
                'verbose_name_plural': 'دوره های خریداری شده',
            },
        ),
    ]
