# Generated by Django 3.2.3 on 2021-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
