# Generated by Django 3.2.3 on 2021-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
