# Generated by Django 3.2.3 on 2021-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cart_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='time',
        ),
        migrations.AddField(
            model_name='cart',
            name='_time',
            field=models.DateTimeField(null=True),
        ),
    ]
