# Generated by Django 3.2.3 on 2021-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210811_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
