# Generated by Django 3.2.3 on 2021-08-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cart__time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='_time',
            new_name='time',
        ),
    ]
