# Generated by Django 3.2.3 on 2021-08-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename__time_cart_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='time',
        ),
    ]
