# Generated by Django 3.2.3 on 2021-08-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cart_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
