# Generated by Django 3.2.3 on 2021-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editeduser',
            name='email',
            field=models.EmailField(help_text='ایمیل شما نباید در سامانه موجود باشد', max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='number',
            field=models.CharField(help_text='شماره تلفون خود را با دقت وارد نمایید', max_length=12, verbose_name='شماره تلفون'),
        ),
    ]
