# Generated by Django 3.2.3 on 2021-07-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaccount', '0002_auto_20210702_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editeduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='number',
            field=models.CharField(help_text='شماره تلفون خود را با دقت وارد نمایید', max_length=12, unique=True, verbose_name='شماره تلفون'),
        ),
        migrations.AlterField(
            model_name='editeduser',
            name='username',
            field=models.CharField(help_text='در صورت تمایل برای خود نام کاربری قرار دهید', max_length=150),
        ),
    ]
