# Generated by Django 3.2.3 on 2021-07-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaccount', '0003_auto_20210712_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='editeduser',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='editeduser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'آقا'), ('f', 'خانم')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
    ]
